# Generated by Django 2.2 on 2019-05-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_run_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='run',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='run',
            name='seconds',
        ),
        migrations.AddField(
            model_name='run',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
