# Generated by Django 2.2 on 2019-05-20 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_auto_20190516_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
