# Generated by Django 2.2 on 2019-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
    ]
