# Generated by Django 2.2 on 2019-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_run_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='run',
            name='run_type',
            field=models.CharField(blank=True, choices=[('Road run', 'Road run'), ('Trail run', 'Trail run'), ('Race', 'Race'), ('Treadmill', 'Treadmill')], default=None, max_length=10, null=True),
        ),
    ]
