# Generated by Django 2.2.2 on 2019-06-29 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_auto_20190528_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='start_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='gear',
            name='start_units',
            field=models.CharField(choices=[('mi', 'mi'), ('km', 'km')], default='mi', max_length=2),
        ),
    ]
