# Generated by Django 2.2.3 on 2019-08-14 23:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0008_auto_20190629_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gear',
            name='start_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
