# Generated by Django 2.2.3 on 2019-08-15 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0009_auto_20190814_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gear',
            name='date_retired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
