# Generated by Django 2.2.4 on 2019-08-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0010_auto_20190815_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-run_date']},
        ),
        migrations.RemoveField(
            model_name='run',
            name='date',
        ),
        migrations.RemoveField(
            model_name='run',
            name='time',
        ),
    ]
